name:                borrow
version:             0.1.0.0
github:              "lucadp19/borrow"
license:             BSD3
author:              "Luca De Paulis"
maintainer:          "luca.dp1909@gmail.com"
copyright:           "2022 Luca De Paulis"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lang#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- mtl
- transformers
- megaparsec
- parser-combinators
- optparse-applicative
- pretty-simple

library:
  source-dirs: src

executables:
  borrow:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - borrow

# tests:
#   lang-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - lang
